name: Tests CI
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: sudo apt-get update
      - run: sudo make install
      - run: sudo make install-extra
      - run: |
          sudo apt-get -y install postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo -u postgres psql -c "CREATE DATABASE sner_test"
          sudo -u postgres psql -c "CREATE USER ${USER}"
          mkdir -p /tmp/sner_test_var
      - run: . venv/bin/activate && make lint
      - run: . venv/bin/activate && make coverage
      - run: . venv/bin/activate && make test-extra
